// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6yBGsyYUhDsUqL-xXwP5die0wT5HkQ5I',
    appId: '1:116181058680:android:d1288b27070eceef0ed98d',
    messagingSenderId: '116181058680',
    projectId: 'yum-quick-food-ui',
    databaseURL: 'https://yum-quick-food-ui-default-rtdb.firebaseio.com',
    storageBucket: 'yum-quick-food-ui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRCFR79_6qsi1prSvbqEdzutJGbjw0KE',
    appId: '1:116181058680:ios:8f8766fa21ae86bb0ed98d',
    messagingSenderId: '116181058680',
    projectId: 'yum-quick-food-ui',
    databaseURL: 'https://yum-quick-food-ui-default-rtdb.firebaseio.com',
    storageBucket: 'yum-quick-food-ui.firebasestorage.app',
    androidClientId: '116181058680-fn6cthcbavv0nhqvoekgnglvhtjapb2m.apps.googleusercontent.com',
    iosClientId: '116181058680-7df2gqnifkukp6hp6v2qanmeaamrjrqt.apps.googleusercontent.com',
    iosBundleId: 'com.yumquick.com',
  );

}